### ISSUE TITLE
Clearer, more granular configuration needed

### ISSUE THREAD

**Issue by dgw** [birkett/CloudFlare-DDNS-Updater#1] opened 2015-01-26 03:06 UTC
I found this project as a possible replacement for FlareDNS, which recently seems to have stopped updating my Windows machines properly. It seemed like it would be a pretty simple drop-in, configure, and go, but that hasn't been my experience.

The documentation doesn't really say what putting in "your details" will do, but from reading the code it looks like the app updates every single A record in the zone you give it to the current machine's public IP. Thankfully I didn't configure it correctly, or most of my websites would have been knocked offline until I put the right IPs back in.

Am I missing a way to specify the zone (e.g. `mydomain.name`) and then specify only a single subdomain (e.g. `windows1.mydomain.name`) to be updated?

I hate to misuse the issue tracker like this, but since finding @birkett on Twitter didn't work out I needed to just get in touch however I could.

**Comment by birkett** [comment] 2015-01-26 13:04
Filtering and selecting individual domains is a planned feature. I plan on working on this further, soon.

**Comment by bnosie** [comment] 2015-03-17 15:03
Any progress?  I would really like a Windows client to update CloudFlare, without having to install perl or php on my Windows server, but only need to update 5 hosts in a zone with about 20 other records.

**Comment by birkett** [comment] 2015-03-17 15:07
zfanta kindly committed a small patch to add checkboxes. This was merged in yesterday, and allows you to select specific hosts to update. That should get you up and running.

There's more work happening on this, which will be merged soon.

**Comment by bnosie** [comment] 2015-03-17 16:38
That's great!  Do you have a build?  I only see the source and the initial release.

**Comment by birkett** [comment] 2015-03-17 16:40
To clarify further - filling in the "Domain" box in the settings will correctly limit the update process to only that root domain. "example.com" in the Domain box will fetch and update A records for "*.example.com", all other domains on the account will be ignored.

With zfanta's commit yesterday, there are now additional checkboxes in the host list. Only checked hosts will be updated.

The process is a little bugged right now, as the checked items are not saved, and will revert to unchecked after every update. I'm working to fix this right now, and will push some new binaries tonight.

**Comment by bnosie** [comment] 2015-03-17 16:48
Awesome. Thanks for your work on this.

**Comment by birkett** [comment] 2015-03-17 17:44
Binaries added to the releases tab.
I will keep this issue open for now. I still need to create the proper documentation, and possibly revisit the code for this. It could be cleaner. (possibly use an OnChanged callback on the checkboxes).

**Comment by birkett** [comment] 2015-03-19 20:34
Closing this now that the README has been updated, and filtering / service support is working as intended. 

The contents of README will eventually be split into Wiki pages.

**Closed as completed by birkett** 2015-03-19 20:34 UTC
Labels: enhancement
